services:
  postgresdb:
    image: postgres:15  # Use a specific version for stability
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: postgresdb
      DB_USER: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
    volumes:
      - .:/app
    command: >
        sh -c "npx sequelize-cli db:migrate && node index.js"

volumes:
  db:
