services:
  postgresdb:
    image: postgres:15  # Use a specific version for stability
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data # create a volume for storing database datas

  app:
    depends_on:
      - postgresdb
    build: 
      context: . # Use the current dir during build
      dockerfile: ./Dockerfile # Help find the dockerfile
    restart: unless-stopped # Sync changes instantly without re-running the container
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: postgresdb
      DB_USER: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
    volumes:
      - .:/app # Mount the entire datemydaughter dir to /app
      - /app/node_modules # Keep docker container's node_modules, creates a named volume for node_modules
    command: >
        sh -c "npx sequelize-cli db:migrate && node index.js"

volumes:
  db:
